FROM python:3.10-slim
RUN apt-get update && apt-get install -y git libpq-dev gcc && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir dbt-postgres==1.5.0
WORKDIR /usr/app/dbt_project
ENTRYPOINT ["dbt"]
