services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crypto_data
    ports:
      - "5432:5432"

  ingestion-app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: crypto_data
      DLQ_DIR: /app/data/dlq
      PYTHONUNBUFFERED: 1
    volumes:
      - ./data/dlq:/app/data/dlq
    depends_on:
      - db
